//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  category: Category;
  categoryConnection: CategoryConnection;
  workItem: WorkItem;
  workItemConnection: WorkItemConnection;
  siteSection: SiteSection;
  siteSectionConnection: SiteSectionConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCategoryArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryCategoryConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<CategoryFilter>;
};


export type QueryWorkItemArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryWorkItemConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<WorkItemFilter>;
};


export type QuerySiteSectionArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSectionConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSectionFilter>;
};

export type DocumentFilter = {
  category?: InputMaybe<CategoryFilter>;
  workItem?: InputMaybe<WorkItemFilter>;
  siteSection?: InputMaybe<SiteSectionFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Category | WorkItem | SiteSectionHero | SiteSectionAbout | SiteSectionSkills | SiteSectionExperience | SiteSectionTestimonials | SiteSectionResume | SiteSectionContact | SiteSectionNavigation | Folder;

export type Category = Node & Document & {
  __typename?: 'Category';
  name: Scalars['String']['output'];
  description: Scalars['String']['output'];
  tools?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  icon?: Maybe<Scalars['String']['output']>;
  slug?: Maybe<Scalars['String']['output']>;
  sortOrder?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type CategoryFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  tools?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  sortOrder?: InputMaybe<NumberFilter>;
};

export type CategoryConnectionEdges = {
  __typename?: 'CategoryConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Category>;
};

export type CategoryConnection = Connection & {
  __typename?: 'CategoryConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<CategoryConnectionEdges>>>;
};

export type WorkItemCategory = Category;

export type WorkItem = Node & Document & {
  __typename?: 'WorkItem';
  title: Scalars['String']['output'];
  category: WorkItemCategory;
  image: Scalars['String']['output'];
  alt?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
  tech?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type WorkItemCategoryFilter = {
  category?: InputMaybe<CategoryFilter>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type WorkItemFilter = {
  title?: InputMaybe<StringFilter>;
  category?: InputMaybe<WorkItemCategoryFilter>;
  image?: InputMaybe<ImageFilter>;
  alt?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  tech?: InputMaybe<StringFilter>;
};

export type WorkItemConnectionEdges = {
  __typename?: 'WorkItemConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<WorkItem>;
};

export type WorkItemConnection = Connection & {
  __typename?: 'WorkItemConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<WorkItemConnectionEdges>>>;
};

export type SiteSectionHero = Node & Document & {
  __typename?: 'SiteSectionHero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  headingLine1?: Maybe<Scalars['String']['output']>;
  headingHighlight?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  locationText?: Maybe<Scalars['String']['output']>;
  profileImage?: Maybe<Scalars['String']['output']>;
  badgeYears?: Maybe<Scalars['Float']['output']>;
  badgeYearsText?: Maybe<Scalars['String']['output']>;
  badgeCraftText?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSectionAboutStats = {
  __typename?: 'SiteSectionAboutStats';
  value?: Maybe<Scalars['Float']['output']>;
  suffix?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
};

export type SiteSectionAbout = Node & Document & {
  __typename?: 'SiteSectionAbout';
  label?: Maybe<Scalars['String']['output']>;
  titleLine1?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  paragraphs?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  stats?: Maybe<Array<Maybe<SiteSectionAboutStats>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSectionSkillsSkills = {
  __typename?: 'SiteSectionSkillsSkills';
  name?: Maybe<Scalars['String']['output']>;
  level?: Maybe<Scalars['Float']['output']>;
};

export type SiteSectionSkillsExpertise = {
  __typename?: 'SiteSectionSkillsExpertise';
  name?: Maybe<Scalars['String']['output']>;
  level?: Maybe<Scalars['Float']['output']>;
};

export type SiteSectionSkills = Node & Document & {
  __typename?: 'SiteSectionSkills';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  skills?: Maybe<Array<Maybe<SiteSectionSkillsSkills>>>;
  expertise?: Maybe<Array<Maybe<SiteSectionSkillsExpertise>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSectionExperienceExperience = {
  __typename?: 'SiteSectionExperienceExperience';
  company?: Maybe<Scalars['String']['output']>;
  role?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  achievement?: Maybe<Scalars['String']['output']>;
};

export type SiteSectionExperience = Node & Document & {
  __typename?: 'SiteSectionExperience';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  experience?: Maybe<Array<Maybe<SiteSectionExperienceExperience>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSectionTestimonialsTestimonials = {
  __typename?: 'SiteSectionTestimonialsTestimonials';
  name?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  quote?: Maybe<Scalars['String']['output']>;
  rating?: Maybe<Scalars['Float']['output']>;
};

export type SiteSectionTestimonials = Node & Document & {
  __typename?: 'SiteSectionTestimonials';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  testimonials?: Maybe<Array<Maybe<SiteSectionTestimonialsTestimonials>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSectionResumeExperience = {
  __typename?: 'SiteSectionResumeExperience';
  role?: Maybe<Scalars['String']['output']>;
  company?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  bullets?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type SiteSectionResumeFreelanceExperience = {
  __typename?: 'SiteSectionResumeFreelanceExperience';
  role?: Maybe<Scalars['String']['output']>;
  company?: Maybe<Scalars['String']['output']>;
  duration?: Maybe<Scalars['String']['output']>;
  bullets?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type SiteSectionResumeTechnicalSkills = {
  __typename?: 'SiteSectionResumeTechnicalSkills';
  threeDAndRendering?: Maybe<Scalars['String']['output']>;
  graphicDesign?: Maybe<Scalars['String']['output']>;
  video?: Maybe<Scalars['String']['output']>;
  additional?: Maybe<Scalars['String']['output']>;
};

export type SiteSectionResumeEducation = {
  __typename?: 'SiteSectionResumeEducation';
  degree?: Maybe<Scalars['String']['output']>;
  institution?: Maybe<Scalars['String']['output']>;
};

export type SiteSectionResume = Node & Document & {
  __typename?: 'SiteSectionResume';
  name?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  contactLine?: Maybe<Scalars['String']['output']>;
  summary?: Maybe<Scalars['String']['output']>;
  coreCompetencies?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  experience?: Maybe<Array<Maybe<SiteSectionResumeExperience>>>;
  freelanceExperience?: Maybe<Array<Maybe<SiteSectionResumeFreelanceExperience>>>;
  technicalSkills?: Maybe<SiteSectionResumeTechnicalSkills>;
  education?: Maybe<Array<Maybe<SiteSectionResumeEducation>>>;
  languages?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSectionContact = Node & Document & {
  __typename?: 'SiteSectionContact';
  eyebrow?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  titleHighlight?: Maybe<Scalars['String']['output']>;
  subtitle?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  whatsapp?: Maybe<Scalars['String']['output']>;
  linkedin?: Maybe<Scalars['String']['output']>;
  location?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSectionNavigationLinks = {
  __typename?: 'SiteSectionNavigationLinks';
  label?: Maybe<Scalars['String']['output']>;
  href?: Maybe<Scalars['String']['output']>;
  hash?: Maybe<Scalars['String']['output']>;
};

export type SiteSectionNavigation = Node & Document & {
  __typename?: 'SiteSectionNavigation';
  links?: Maybe<Array<Maybe<SiteSectionNavigationLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSection = SiteSectionHero | SiteSectionAbout | SiteSectionSkills | SiteSectionExperience | SiteSectionTestimonials | SiteSectionResume | SiteSectionContact | SiteSectionNavigation;

export type SiteSectionHeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  headingLine1?: InputMaybe<StringFilter>;
  headingHighlight?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  locationText?: InputMaybe<StringFilter>;
  profileImage?: InputMaybe<ImageFilter>;
  badgeYears?: InputMaybe<NumberFilter>;
  badgeYearsText?: InputMaybe<StringFilter>;
  badgeCraftText?: InputMaybe<StringFilter>;
};

export type SiteSectionAboutStatsFilter = {
  value?: InputMaybe<NumberFilter>;
  suffix?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
};

export type SiteSectionAboutFilter = {
  label?: InputMaybe<StringFilter>;
  titleLine1?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  paragraphs?: InputMaybe<StringFilter>;
  stats?: InputMaybe<SiteSectionAboutStatsFilter>;
};

export type SiteSectionSkillsSkillsFilter = {
  name?: InputMaybe<StringFilter>;
  level?: InputMaybe<NumberFilter>;
};

export type SiteSectionSkillsExpertiseFilter = {
  name?: InputMaybe<StringFilter>;
  level?: InputMaybe<NumberFilter>;
};

export type SiteSectionSkillsFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  skills?: InputMaybe<SiteSectionSkillsSkillsFilter>;
  expertise?: InputMaybe<SiteSectionSkillsExpertiseFilter>;
};

export type SiteSectionExperienceExperienceFilter = {
  company?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  achievement?: InputMaybe<StringFilter>;
};

export type SiteSectionExperienceFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  experience?: InputMaybe<SiteSectionExperienceExperienceFilter>;
};

export type SiteSectionTestimonialsTestimonialsFilter = {
  name?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  quote?: InputMaybe<StringFilter>;
  rating?: InputMaybe<NumberFilter>;
};

export type SiteSectionTestimonialsFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  testimonials?: InputMaybe<SiteSectionTestimonialsTestimonialsFilter>;
};

export type SiteSectionResumeExperienceFilter = {
  role?: InputMaybe<StringFilter>;
  company?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  bullets?: InputMaybe<StringFilter>;
};

export type SiteSectionResumeFreelanceExperienceFilter = {
  role?: InputMaybe<StringFilter>;
  company?: InputMaybe<StringFilter>;
  duration?: InputMaybe<StringFilter>;
  bullets?: InputMaybe<StringFilter>;
};

export type SiteSectionResumeTechnicalSkillsFilter = {
  threeDAndRendering?: InputMaybe<StringFilter>;
  graphicDesign?: InputMaybe<StringFilter>;
  video?: InputMaybe<StringFilter>;
  additional?: InputMaybe<StringFilter>;
};

export type SiteSectionResumeEducationFilter = {
  degree?: InputMaybe<StringFilter>;
  institution?: InputMaybe<StringFilter>;
};

export type SiteSectionResumeFilter = {
  name?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  contactLine?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  coreCompetencies?: InputMaybe<StringFilter>;
  experience?: InputMaybe<SiteSectionResumeExperienceFilter>;
  freelanceExperience?: InputMaybe<SiteSectionResumeFreelanceExperienceFilter>;
  technicalSkills?: InputMaybe<SiteSectionResumeTechnicalSkillsFilter>;
  education?: InputMaybe<SiteSectionResumeEducationFilter>;
  languages?: InputMaybe<StringFilter>;
};

export type SiteSectionContactFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  titleHighlight?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  whatsapp?: InputMaybe<StringFilter>;
  linkedin?: InputMaybe<StringFilter>;
  location?: InputMaybe<StringFilter>;
};

export type SiteSectionNavigationLinksFilter = {
  label?: InputMaybe<StringFilter>;
  href?: InputMaybe<StringFilter>;
  hash?: InputMaybe<StringFilter>;
};

export type SiteSectionNavigationFilter = {
  links?: InputMaybe<SiteSectionNavigationLinksFilter>;
};

export type SiteSectionFilter = {
  hero?: InputMaybe<SiteSectionHeroFilter>;
  about?: InputMaybe<SiteSectionAboutFilter>;
  skills?: InputMaybe<SiteSectionSkillsFilter>;
  experience?: InputMaybe<SiteSectionExperienceFilter>;
  testimonials?: InputMaybe<SiteSectionTestimonialsFilter>;
  resume?: InputMaybe<SiteSectionResumeFilter>;
  contact?: InputMaybe<SiteSectionContactFilter>;
  navigation?: InputMaybe<SiteSectionNavigationFilter>;
};

export type SiteSectionConnectionEdges = {
  __typename?: 'SiteSectionConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteSection>;
};

export type SiteSectionConnection = Connection & {
  __typename?: 'SiteSectionConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteSectionConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateCategory: Category;
  createCategory: Category;
  updateWorkItem: WorkItem;
  createWorkItem: WorkItem;
  updateSiteSection: SiteSection;
  createSiteSection: SiteSection;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateCategoryArgs = {
  relativePath: Scalars['String']['input'];
  params: CategoryMutation;
};


export type MutationCreateCategoryArgs = {
  relativePath: Scalars['String']['input'];
  params: CategoryMutation;
};


export type MutationUpdateWorkItemArgs = {
  relativePath: Scalars['String']['input'];
  params: WorkItemMutation;
};


export type MutationCreateWorkItemArgs = {
  relativePath: Scalars['String']['input'];
  params: WorkItemMutation;
};


export type MutationUpdateSiteSectionArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSectionMutation;
};


export type MutationCreateSiteSectionArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSectionMutation;
};

export type DocumentUpdateMutation = {
  category?: InputMaybe<CategoryMutation>;
  workItem?: InputMaybe<WorkItemMutation>;
  siteSection?: InputMaybe<SiteSectionMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  category?: InputMaybe<CategoryMutation>;
  workItem?: InputMaybe<WorkItemMutation>;
  siteSection?: InputMaybe<SiteSectionMutation>;
};

export type CategoryMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  tools?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  icon?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  sortOrder?: InputMaybe<Scalars['Float']['input']>;
};

export type WorkItemMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  tech?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteSectionHeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  headingLine1?: InputMaybe<Scalars['String']['input']>;
  headingHighlight?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  locationText?: InputMaybe<Scalars['String']['input']>;
  profileImage?: InputMaybe<Scalars['String']['input']>;
  badgeYears?: InputMaybe<Scalars['Float']['input']>;
  badgeYearsText?: InputMaybe<Scalars['String']['input']>;
  badgeCraftText?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSectionAboutStatsMutation = {
  value?: InputMaybe<Scalars['Float']['input']>;
  suffix?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSectionAboutMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  titleLine1?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  paragraphs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  stats?: InputMaybe<Array<InputMaybe<SiteSectionAboutStatsMutation>>>;
};

export type SiteSectionSkillsSkillsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  level?: InputMaybe<Scalars['Float']['input']>;
};

export type SiteSectionSkillsExpertiseMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  level?: InputMaybe<Scalars['Float']['input']>;
};

export type SiteSectionSkillsMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  skills?: InputMaybe<Array<InputMaybe<SiteSectionSkillsSkillsMutation>>>;
  expertise?: InputMaybe<Array<InputMaybe<SiteSectionSkillsExpertiseMutation>>>;
};

export type SiteSectionExperienceExperienceMutation = {
  company?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  achievement?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSectionExperienceMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  experience?: InputMaybe<Array<InputMaybe<SiteSectionExperienceExperienceMutation>>>;
};

export type SiteSectionTestimonialsTestimonialsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  quote?: InputMaybe<Scalars['String']['input']>;
  rating?: InputMaybe<Scalars['Float']['input']>;
};

export type SiteSectionTestimonialsMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  testimonials?: InputMaybe<Array<InputMaybe<SiteSectionTestimonialsTestimonialsMutation>>>;
};

export type SiteSectionResumeExperienceMutation = {
  role?: InputMaybe<Scalars['String']['input']>;
  company?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  bullets?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteSectionResumeFreelanceExperienceMutation = {
  role?: InputMaybe<Scalars['String']['input']>;
  company?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['String']['input']>;
  bullets?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteSectionResumeTechnicalSkillsMutation = {
  threeDAndRendering?: InputMaybe<Scalars['String']['input']>;
  graphicDesign?: InputMaybe<Scalars['String']['input']>;
  video?: InputMaybe<Scalars['String']['input']>;
  additional?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSectionResumeEducationMutation = {
  degree?: InputMaybe<Scalars['String']['input']>;
  institution?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSectionResumeMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  contactLine?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  coreCompetencies?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  experience?: InputMaybe<Array<InputMaybe<SiteSectionResumeExperienceMutation>>>;
  freelanceExperience?: InputMaybe<Array<InputMaybe<SiteSectionResumeFreelanceExperienceMutation>>>;
  technicalSkills?: InputMaybe<SiteSectionResumeTechnicalSkillsMutation>;
  education?: InputMaybe<Array<InputMaybe<SiteSectionResumeEducationMutation>>>;
  languages?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SiteSectionContactMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  titleHighlight?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  whatsapp?: InputMaybe<Scalars['String']['input']>;
  linkedin?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSectionNavigationLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  href?: InputMaybe<Scalars['String']['input']>;
  hash?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSectionNavigationMutation = {
  links?: InputMaybe<Array<InputMaybe<SiteSectionNavigationLinksMutation>>>;
};

export type SiteSectionMutation = {
  hero?: InputMaybe<SiteSectionHeroMutation>;
  about?: InputMaybe<SiteSectionAboutMutation>;
  skills?: InputMaybe<SiteSectionSkillsMutation>;
  experience?: InputMaybe<SiteSectionExperienceMutation>;
  testimonials?: InputMaybe<SiteSectionTestimonialsMutation>;
  resume?: InputMaybe<SiteSectionResumeMutation>;
  contact?: InputMaybe<SiteSectionContactMutation>;
  navigation?: InputMaybe<SiteSectionNavigationMutation>;
};


export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
  
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  